# .blade.yml
load_paths:
  - tmp
  - app/assets/javascripts
  - app/assets/html
  - test/src
  - vendor/jquery-rails/vendor/assets/javascripts/

logical_paths:
  - _header_script_js.js
  - jquery.js
  - frontendframework.js
  - frontendframework-tests.js
